### ISSUE TITLE
Repeat skips include_context calls

### ISSUE THREAD

**Issue by ghost** [rstacruz/rspec-repeat#2]
I have an include_context call before my it statement that I want to repeat on failure, this include_context contains a before_all. When the test fails, the it-statement is reran, but the before_all inside the include_context is not. Also if there is a failure in the include_context, then the test is not reran at all. Here is an example

```
describe "Cool Operation",  do
  include RSpec::Repeat

  around do |example|
     repeat example, 10.times
  end

  include_context('cool setup - before all')

  it 'does cool stuff' do
    expect(@var_setup_in_before_all).to eq(CoolObject)
  end
end
```
Does this gem support this feature?

**Comment by rstacruz** [comment]
~~Sorry, I'm not aware if it does;~~ RSpec::Repeat simply does `example.run` which I think takes contexts into account, ~~but I don't have tests to prove this.~~

(edit: see below)

**Comment by rstacruz** [comment]
okay, just checked. contexts are supported, and I'm writing some test cases for it.

**Comment by rstacruz** [comment]
Also, `before :all` will **not** be retried, but `before :each` will. Consider this example:

```rb
describe 'stubborn tests' do
  # These will only be ran once!
  before(:all) { NumberFetcher.mock! }
  after(:all) { NumberFetcher.unmock! }

  it 'works' do
    expect(2).to eq NumberFetcher.get
  end

  it 'works sometimes', :repeat_me do
    expect(rand(10)).to eq NumberFetcher.get
  end
end
```

When RSpec runs this, you're only expecting it to run `before(:all)` once, ever. Running a `before(:all)` block twice (esp. without running `after(:all)`) may have some unintentional side effects.

Consider using `before :each` instead.
